language: python
python:
  - "3.6"
install:
  - pip install pytest
  - pip install threatconnect
  - pip install tcex
  - pip install bs4
  - pip install requests
  - pip install inflect
script:
  - make uptcex
